
title: Beethoven in the House
tag: A Collaborative Digital Musicology Project
email: email@domestic-beethoven.eu
description: A digital investigation into domestic music performance in the 19th century.

# ! ! -- BASEURL SETTINGS -- ! !

#baseurl: "/dbsite"
baseurl: ""

url: "http://domestic-beethoven.eu"

# github_username:  mss2221

# BUILD SETTINGS
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed


collections:
    verovio:
      output: true
      permalink: /verovio/:path/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
