
title: Beethoven in the House
tag: A Collaborative Digital Musicology Project
email: info@domestic-beethoven.eu
description:  Digital Studies of Domestic Music Arrangements


# TODO: add project email address

# ! ! -- BASEURL SETTINGS -- ! !

baseurl: "/dbsite"
#baseurl: ""

url: "http://domestic-beethoven.eu"

# github_username:  mss2221

# BUILD SETTINGS
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

# example of using a COLLECTION in jekyll
#
# collections:
#     verovio:
#       output: true
#       permalink: /verovio/:path/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
